version: 2

# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
defaults: &defaults
  docker:
    - image: cimg/go:1.19
  working_directory: /home/circleci/go/src/github.com/weaveworks/common

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - lint
    - check-protos
    - test

jobs:
  lint:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Lint
        command: |
          make lint

  check-protos:
    machine: # executor type
      image: ubuntu-2204:2022.10.2
    working_directory: /home/circleci/go/src/github.com/weaveworks/common
    steps:
    - checkout
    - run:
        name: Check generated protobuf files
        command: |
          go version
          go mod vendor
          make check-protos

  test:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Test
        command: |
          make test
