// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/httpgrpc.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types/httpgrpc.proto

It has these top-level messages:
	HTTPRequest
	HTTPResponse
	Header
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HTTPRequest struct {
	Method  string    `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Url     string    `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Headers []*Header `protobuf:"bytes,3,rep,name=headers" json:"headers,omitempty"`
	Body    []byte    `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *HTTPRequest) Reset()                    { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string            { return proto.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()               {}
func (*HTTPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HTTPRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPRequest) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type HTTPResponse struct {
	Code    int32     `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Headers []*Header `protobuf:"bytes,2,rep,name=headers" json:"headers,omitempty"`
	Body    []byte    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *HTTPResponse) Reset()                    { *m = HTTPResponse{} }
func (m *HTTPResponse) String() string            { return proto.CompactTextString(m) }
func (*HTTPResponse) ProtoMessage()               {}
func (*HTTPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HTTPResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HTTPResponse) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Header struct {
	Key    string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Header) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*HTTPRequest)(nil), "types.HTTPRequest")
	proto.RegisterType((*HTTPResponse)(nil), "types.HTTPResponse")
	proto.RegisterType((*Header)(nil), "types.Header")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HTTP service

type HTTPClient interface {
	Handle(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
}

type hTTPClient struct {
	cc *grpc.ClientConn
}

func NewHTTPClient(cc *grpc.ClientConn) HTTPClient {
	return &hTTPClient{cc}
}

func (c *hTTPClient) Handle(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	out := new(HTTPResponse)
	err := grpc.Invoke(ctx, "/types.HTTP/Handle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HTTP service

type HTTPServer interface {
	Handle(context.Context, *HTTPRequest) (*HTTPResponse, error)
}

func RegisterHTTPServer(s *grpc.Server, srv HTTPServer) {
	s.RegisterService(&_HTTP_serviceDesc, srv)
}

func _HTTP_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.HTTP/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPServer).Handle(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HTTP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.HTTP",
	HandlerType: (*HTTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _HTTP_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/httpgrpc.proto",
}

func init() { proto.RegisterFile("types/httpgrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0xcd, 0x25, 0x17, 0xb9, 0xb9, 0x13, 0x64, 0x14, 0x59, 0xac, 0x42, 0x1a, 0x53, 0x45,
	0xc8, 0x95, 0x96, 0x36, 0x29, 0x65, 0xb9, 0x5e, 0x72, 0xee, 0x60, 0xc0, 0x78, 0xbb, 0xee, 0x6e,
	0x84, 0xfc, 0x7b, 0xd9, 0xd9, 0x1c, 0xc6, 0xce, 0xee, 0xcd, 0x9b, 0x61, 0xbe, 0x37, 0x03, 0xb7,
	0x7e, 0x32, 0xe4, 0x1e, 0x7b, 0xef, 0xcd, 0xbb, 0x35, 0x6f, 0xb5, 0xb1, 0xda, 0x6b, 0x5c, 0xb3,
	0x5b, 0x7a, 0xd8, 0xb6, 0x87, 0xc3, 0x8b, 0xa4, 0xaf, 0x91, 0x9c, 0xc7, 0x3b, 0xc8, 0x3f, 0xc9,
	0xf7, 0x5a, 0x89, 0xa4, 0x48, 0xaa, 0x8d, 0x9c, 0x2b, 0xbc, 0x86, 0x74, 0xb4, 0x83, 0x58, 0xb1,
	0x19, 0x24, 0x3e, 0xc0, 0x65, 0x4f, 0x9d, 0x22, 0xeb, 0x44, 0x5a, 0xa4, 0xd5, 0xb6, 0xb9, 0xaa,
	0x79, 0x63, 0xdd, 0xb2, 0x2b, 0xcf, 0x5d, 0x44, 0xc8, 0x8e, 0x5a, 0x4d, 0x22, 0x2b, 0x92, 0x6a,
	0x27, 0x59, 0x97, 0xaf, 0xb0, 0x8b, 0x54, 0x67, 0xf4, 0xc9, 0x51, 0x98, 0x79, 0xd6, 0x8a, 0x18,
	0xba, 0x96, 0xac, 0x97, 0x80, 0xd5, 0xbf, 0x00, 0xe9, 0x02, 0xd0, 0x40, 0x1e, 0xc7, 0x42, 0xf2,
	0x0f, 0x9a, 0xe6, 0x73, 0x82, 0x0c, 0x37, 0x7e, 0x77, 0xc3, 0x48, 0x71, 0xef, 0x46, 0xce, 0x55,
	0xf3, 0x04, 0x59, 0x08, 0x85, 0x7b, 0xc8, 0xdb, 0xee, 0xa4, 0x06, 0x42, 0x3c, 0x13, 0x7f, 0x3f,
	0x74, 0x7f, 0xf3, 0xc7, 0x8b, 0xf9, 0xcb, 0x8b, 0x63, 0xce, 0x5f, 0xdd, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xf5, 0x19, 0x53, 0x98, 0x6d, 0x01, 0x00, 0x00,
}
