---
# Set up Weave Net.

- name: install weave net
  get_url:
    url: https://git.io/weave
    dest: /usr/local/bin/weave
    mode: 0555

- name: stop weave net
  command: weave stop

- name: start weave net
  command: weave launch

- name: get weave net's status
  command: weave status
  changed_when: false
  register: weave_status
  tags:
    - output

- name: print outpout of `weave status`
  debug: msg="{{ weave_status.stdout_lines }}"
  tags:
    - output
