name: CI
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # We need history so that we can limit issues reported by golangci-lint to those after a certain commit.
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.17.13
      - name: Set up golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.47.3
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Check protos
        run: |
          go mod vendor
          make check-protos
